name: Packaage

on:
  push:
    tags: "*"

jobs:
  package:
    runs-on: ubuntu-latest
    container: heliumsystems/builder-erlang:2

    steps:
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_SECRET }}

      - name: Name Release
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build and push
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: runner
          tags: |
            team-helium/blockchain-http:${{steps.vars.output.tag}}
            team-helium/blockchain-http:latest

      - name: Image digest
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: echo ${{ steps.docker_build.outputs.digest }}
